# Generated by Django 3.1.1 on 2021-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_pelcon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('coursename', models.CharField(max_length=100)),
                ('yos', models.CharField(max_length=100)),
            ],
        ),
    ]
